# DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-daemonset
spec:
  selector:
    matchLabels:
      app: hello-daemon
  template:
    metadata:
      labels:
        app: hello-daemon
    spec:
      containers:
        - name: hello-container
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - while true; do echo "Hello from $(hostname)"; sleep 60; done
---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-statefulset
spec:
  serviceName: "hello-service"
  replicas: 3
  selector:
    matchLabels:
      app: hello-stateful
  template:
    metadata:
      labels:
        app: hello-stateful
    spec:
      containers:
        - name: hello-container
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - echo "Hello from pod $$(hostname)"; sleep 300
---
# Job
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
        - name: hello-container
          image: busybox:1.36
          command: ["echo", "Hello from Kubernetes Job"]
      restartPolicy: Never
  backoffLimit: 4
---
# CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: time-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: time-container
              image: busybox:1.36
              command:
                - /bin/sh
                - -c
                - echo "Current time: $(date)"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
---
# Второй CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: custom-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: custom-container
              image: busybox:1.36
              command:
                - /bin/sh
                - -c
                - echo "Custom message at $(date)"
          restartPolicy: OnFailure