apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    type: web-server
spec:
  containers:
    - name: nginx-container
      image: nginx:1.23
      ports:
        - containerPort: 80  # Порт, который открывает контейнер